// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// logLikelihood
double logLikelihood(double theta, IntegerVector Profiles, int numProfiles, int numLoci, List freqs);
RcppExport SEXP _ConStruct_logLikelihood(SEXP thetaSEXP, SEXP ProfilesSEXP, SEXP numProfilesSEXP, SEXP numLociSEXP, SEXP freqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Profiles(ProfilesSEXP);
    Rcpp::traits::input_parameter< int >::type numProfiles(numProfilesSEXP);
    Rcpp::traits::input_parameter< int >::type numLoci(numLociSEXP);
    Rcpp::traits::input_parameter< List >::type freqs(freqsSEXP);
    rcpp_result_gen = Rcpp::wrap(logLikelihood(theta, Profiles, numProfiles, numLoci, freqs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ConStruct_logLikelihood", (DL_FUNC) &_ConStruct_logLikelihood, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ConStruct(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
