# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logLikelihood <- function(theta, Profiles, numProfiles, numLoci, freqs) {
    .Call(`_ConStruct_logLikelihood`, theta, Profiles, numProfiles, numLoci, freqs)
}

logLikelihoodCosang <- function(theta, C, r, Profiles, numProfiles, numLoci, freqs) {
    .Call(`_ConStruct_logLikelihoodCosang`, theta, C, r, Profiles, numProfiles, numLoci, freqs)
}

logLikelihoodCosangMat <- function(theta, C, r, Profiles, numProfiles, numLoci, freqs) {
    .Call(`_ConStruct_logLikelihoodCosangMat`, theta, C, r, Profiles, numProfiles, numLoci, freqs)
}

